# Generated by Django 4.2.5 on 2023-12-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0005_favorite'),
        ('oauth_app', '0006_alter_restaurant_latitude_alter_restaurant_longitude'),
    ]

    operations = [
    ]
